### PR TITLE
Update jquery-accessible-tabs.js to disable a tab

### PR DESCRIPTION
**Pull request by gdurelle**
So I can make a tab disabled.

ex:
```css
[aria-disabled="true"], [aria-disabled="true"]:hover{
  background-color: #ddd;
  color: #666;
  cursor: not-allowed;
}
```

### CODE REVIEW

**Comment by nico3333fr** [comment]
Hi @gdurelle ,

sorry for the response time, I was sick. 

This is a really good idea, I did not think to this feature.

However, it needed some more updates (for keyboard management, selection of first tab, etc.). I'm going to commit them in a few minutes.

See you,
Nicolas

**Comment by nico3333fr** [comment]
Here are updates : https://github.com/nico3333fr/jquery-accessible-tabs-aria/commit/c0f4d15d65b237cf4cef009a796f99fdd5bf9840

Thanks and see you ;)

**Comment by gdurelle** [comment]
Thank you. amazing work on accessible components, I try use them every time I can.

**Comment by nico3333fr** [comment]
@gdurelle if you have examples of plugins used, do not hesitate to share, I try to make a simple list of where they have been used :)

**Pull request merged**
